# Generated by Django 4.1.10 on 2023-09-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_image', models.ImageField(blank=True, default=' ', null=True, upload_to='uploads/product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.IntegerField()),
            ],
        ),
    ]
