# Generated by Django 4.1.10 on 2023-10-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('productName', models.CharField(max_length=244)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
